name: Run experiment

on: 
  push:
jobs:
  train:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Setup Python
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.8
    - name: Train
      env:
        MLFLOW_TRACKING_URI: azureml://eastus2.experiments.azureml.net/mlflow/v1.0/subscriptions/92c76a2f-0e1c-4216-b65e-abf7a3f34c1e/resourceGroups/keijik-east/providers/Microsoft.MachineLearningServices/workspaces/keijik-east2
      run: |
        pip install -r requirements.txt
        python train.py
