name: Run experiment

on: 
  push:
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Setup Python
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.8
    - run: |
        pip install -r requirements.txt
        python train.py
        
        cat metrics.txt >> report.md
        ml-publish confusion_matrix.png --md >> report.md
        ml-send-comment report.md